### ISSUE TITLE
deis apps:create XXX deletes existing git remote register path

### ISSUE THREAD

**Issue by grandmore** [deis/workflow#335] opened 2016-06-20 19:30 UTC
When creating an app using `deis apps:create NEWAPP` It deletes all the current remote repository paths in my git configuration.

For example.

1. I start developing an app.
2. I create a git repository for it and push code repeatedly until I'm ready to test on Kubernetes.
3. I create a new app on Kubernetes using `deis apps:create NEWAPP`

My original git remote repository information has been removed from my local git and has to be manually re-added. It has been replaced the remote information with the connection to deis.

I assume this is not the expected behaviour. I would expect it to add an additional reference as otherwise I cannot push code to my main repository on Github or Bitbucket.

**Comment by Joshua-Anderson** [comment] 2016-06-20 20:00
In the future, please open a `deis` command line program issues in https://github.com/deis/workflow-cli. 😄 

When running `deis apps:create`, it runs the command `git remote add deis <url>`. This git command should should not delete an existing git remote if exists.

The only time `deis` should an git remote is when you destroy an app (`deis apps:destroy`) with an git remote, when it runs `git remote remove deis`.

I have not observed the behavior of all remotes being deleted after running either of these commands. Could you please give more details about when this happens (perhaps the commands and the terminal output as you run them) so we can try and reproduce.

Thank you!

**Comment by Joshua-Anderson** [comment] 2016-07-18 18:49
Friendly ping!

Do you have any more information about the circumstances surrounding this issue? If I can figure out how to reproduce this, I'd love to get a fix for this into the v2.2 release in the next few days!

**Comment by bacongobbler** [comment] 2016-07-27 20:39
closing due to inactivity. @grandmore please feel free to re-open if you reproduce or have more information to demonstrate this issue. Thanks!

**Closed by bacongobbler** 2016-07-27 20:39 UTC
