### ISSUE TITLE
Ruby buildpack cannot build hiredis

### ISSUE THREAD

**Issue by matthewrudy** [deis/workflow#178] opened 2016-04-20 16:21 UTC
Debug:

* version: workflow-beta-2

So I hit this in my real app.
But I created a minimal rack app that also exhibits the problem

``` bash
git clone https://github.com/matthewrudy/ruby-env.git
cd ruby-env
deis create
git push deis master
...
+ cat -
      ' 'Bundler::InstallError: An error occurred while installing hiredis (0.6.1), and Bundler cannot continue.'
       Bundler::InstallError: An error occurred while installing hiredis (0.6.1), and Bundler cannot continue.
+ read line
+ [[ Make sure that `gem install hiredis -v '0.6.1'` succeeds before bundling. == --* ]]
      ' 'Make sure that `gem install hiredis -v '\''0.6.1'\''` succeeds before bundling.'
+ output_redirect
+ [[ /tmp/slug.tgz == \- ]]
+ cat -
       Make sure that `gem install hiredis -v '0.6.1'` succeeds before bundling.
+ read line
```

but it works fine on heroku
``` bash
heroku create

git push heroku master
....
remote:        Using bundler 1.11.2
remote:        Installing hiredis 0.6.1 with native extensions
remote:        Installing rack 1.6.4
remote:        Bundle complete! 2 Gemfile dependencies, 3 gems now installed.
```

**Comment by bacongobbler** [comment] 2016-04-20 16:38
I could reproduce this on workflow-dev as well. Debug output when the build failed: https://gist.github.com/bacongobbler/eb5590784a829a2ec75f017f5bab4380

**Comment by bacongobbler** [comment] 2016-04-20 16:43
Full logs from a build with `deis create foo -b https://github.com/heroku/heroku-buildpack-ruby` to rule out that our buildpack is outdated: https://gist.github.com/bacongobbler/4b6ecc334d0a00d8a70103701b8c7a83

**Comment by bacongobbler** [comment] 2016-04-20 16:44
This seems to be our smoking gun: https://gist.github.com/bacongobbler/4b6ecc334d0a00d8a70103701b8c7a83#file-gistfile1-txt-L568

**Comment by bacongobbler** [comment] 2016-04-20 16:56
Interestingly enough, `cc` is in the slugbuilder image so I'm not quite sure how this would occur:

```
><> docker run heroku/cedar:14 cc
Unable to find image 'heroku/cedar:14' locally
14: Pulling from heroku/cedar
c78812cd993d: Pull complete 
31912e8b6611: Pull complete 
d57b9580777c: Pull complete 
ec119a0a7c42: Pull complete 
Digest: sha256:a186672c69ba07f03ac264799793134c2d870580ccc667178f2411b1dcf1a5cb
Status: Downloaded newer image for heroku/cedar:14
cc: fatal error: no input files
compilation terminated.
><> docker run --entrypoint=/bin/bash quay.io/deisci/slugbuilder:canary -c "cc"
cc: fatal error: no input files
compilation terminated.
```

ping @smothiki, any ideas on how to debug this?

**Comment by matthewrudy** [comment] 2016-04-24 16:28
So taking a look again at that gist, 
the issue is actually the line before.

``` bash
checking for sys/socket.h... yes
cc -std=c99 -pedantic -c -O3 -fPIC  -Wall -W -Wstrict-prototypes -Wwrite-strings 1  net.c
```

Then it breaks
``` bash
cc: error: 1: No such file or directory
```

So the error is actually caused by something returning a 1 instead of something useful.

On my local mac instead the call is
``` bash
cc -std=c99 -pedantic -c -O3 -fPIC  -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb  net.c
```

And that string `-g -ggdb` would normally comes from

``` bash
DEBUG?= -g -ggdb
```

So, is the slug builder setting a `DEBUG=1` flag somewhere?

**Comment by matthewrudy** [comment] 2016-04-24 16:38
Maybe this

https://github.com/deis/slugbuilder/blob/8dbd543c27251eb7e30164e9403a1b192550182a/manifests/deis-slugbuilder.yaml#L16-L17

**Comment by matthewrudy** [comment] 2016-04-24 16:41
And there was a corresponding issue on hiredis
https://github.com/redis/hiredis/pull/418

So I think that's the issue.

@bacongobbler take a look and see if you think we should remove the `DEBUG=1` or if its just a hiredis issue.

Thanks.

**Comment by bacongobbler** [comment] 2016-04-25 15:22
That definitely sounds like our problem. Looks like we'll have to disable DEBUG during the buildpack compilation. Awesome catch!

**Comment by matthewrudy** [comment] 2016-04-26 03:36
@bacongobbler maybe you can just namespace the `DEBUG` flag

`DEIS_DEBUG=1` is unlikely to tread on anyone's toes

`SLUGBUILDER_DEBUG=1` even more so

**Comment by bacongobbler** [comment] 2016-04-28 20:04
Sounds good. Changing the debug flag to DEIS_DEBUG makes sense.

**Comment by jchauncey** [comment] 2016-05-09 22:16
moving to rc1

**Closed** 2016-05-12 18:04 UTC
Labels: bug, in progress
