### ISSUE TITLE
`PullImageError` on app pods

### ISSUE THREAD

**Issue by arschles** [deis/workflow#100] opened 2015-12-16 21:19 UTC
I created an app with a `git push`, and the launched pod (and later pods launched by subsequent `git push`es) go into `PullImageError` state:

```console
ENG000656:workflow aaronschlesinger$ k get --namespace=wicker-radiator pod
NAME                           READY     STATUS           RESTARTS   AGE
wicker-radiator-v3-web-au7sn   0/1       PullImageError   0          1h
wicker-radiator-v4-web-uc4gz   0/1       PullImageError   0          1h
wicker-radiator-v5-web-iikid   0/1       PullImageError   0          28m
ENG000656:workflow aaronschlesinger$ k describe --namespace=wicker-radiator pod wicker-radiator-v5-web-iikid
Name:				wicker-radiator-v5-web-iikid
Namespace:			wicker-radiator
Image(s):			10.3.0.185:5000/wicker-radiator:v5
Node:				172.17.8.100/172.17.8.100
Start Time:			Wed, 16 Dec 2015 12:48:54 -0800
Labels:				app=wicker-radiator,heritage=deis,type=web,version=v5
Status:				Pending
Reason:				
Message:			
IP:				10.2.76.250
Replication Controllers:	wicker-radiator-v5-web (1/1 replicas created)
Containers:
  wicker-radiator-web:
    Container ID:	
    Image:		10.3.0.185:5000/wicker-radiator:v5
    Image ID:		
    State:		Waiting
      Reason:		PullImageError
    Ready:		False
    Restart Count:	0
    Environment Variables:
Conditions:
  Type		Status
  Ready 	False 
Volumes:
  default-token-m3h32:
    Type:	Secret (a secret that should populate this volume)
    SecretName:	default-token-m3h32
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath				Reason		Message
  ─────────	────────	─────	────			─────────────				──────		───────
  28m		28m		1	{scheduler }							Scheduled	Successfully assigned wicker-radiator-v5-web-iikid to 172.17.8.100
  28m		28m		1	{kubelet 172.17.8.100}	implicitly required container POD	Pulled		Container image "gcr.io/google_containers/pause:0.8.0" already present on machine
  28m		28m		1	{kubelet 172.17.8.100}	implicitly required container POD	Created		Created with docker id cf80574d2123
  28m		28m		1	{kubelet 172.17.8.100}	implicitly required container POD	Started		Started with docker id cf80574d2123
  28m		1s		174	{kubelet 172.17.8.100}	spec.containers{wicker-radiator-web}	Pulling		Pulling image "10.3.0.185:5000/wicker-radiator:v5"
  28m		1s		174	{kubelet 172.17.8.100}	spec.containers{wicker-radiator-web}	Failed		Failed to pull image "10.3.0.185:5000/wicker-radiator:v5": API error (500): invalid registry endpoint https://10.3.0.185:5000/v0/: unable to ping registry endpoint https://10.3.0.185:5000/v0/
v2 ping attempt failed with error: Get https://10.3.0.185:5000/v2/: tls: oversized record received with length 20527
 v1 ping attempt failed with error: Get https://10.3.0.185:5000/v1/_ping: tls: oversized record received with length 20527. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry 10.3.0.185:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/10.3.0.185:5000/ca.crt
```

It looks like a registry issue, possibly related to #99 because the logs therein indicate there may be registry issues also.

**Comment by bacongobbler** [comment] 2015-12-16 22:03
this is a duplicate of #99 so let's keep the debugging in one place. :)

**Closed by bacongobbler** 2015-12-16 22:03 UTC
Labels: bug, showstopper
