### ISSUE TITLE
received unexpected HTTP status: 500 Internal Server Error

### ISSUE THREAD

**Issue by robeferre** [deis/workflow#848] opened 2017-08-08 17:00 UTC
Hi I'm tring to deploy a nodejs app using my docker file that works perfecly on my machine, but I'm receiving this issue when "git push deis branch" when deploing to my cluster at AWS, could someone help me?

```
received unexpected HTTP status: 500 Internal Server Error
remote: 2017/08/08 16:47:14 Error running git receive hook [Build pod exited with code 1, stopping build.]
To ssh://deis-builder.kubernetes.apps.tvglobo.com.br:2222/bancadev.git
 ! [remote rejected] dockerizing -> dockerizing (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@deis-builder.kubernetes.apps.tvglobo.com.br:2222/bancadev.git'
```

Kubernets and deis version
```
kubectl version --short
Client Version: v1.7.3
Server Version: v1.5.7

deis version
v2.16.0
```

#PODS
```
[roberfer@Robertos-MacBook-Pro ~]$ kubectl --namespace=deis get pods
NAME                                     READY     STATUS    RESTARTS   AGE
deis-builder-3921145163-9dczg            1/1       Running   2          1h
deis-controller-4286465232-cfz8p         1/1       Running   3          1h
deis-database-363551994-v26vr            1/1       Running   0          1h
deis-logger-510300457-c78c9              1/1       Running   3          1h
deis-logger-fluentd-0dqc5                1/1       Running   0          1h
deis-logger-fluentd-b0zp9                1/1       Running   0          1h
deis-logger-fluentd-wdq8p                1/1       Running   0          1h
deis-logger-redis-483369825-fqpfn        1/1       Running   0          1h
deis-minio-834471019-251z9               1/1       Running   0          1h
deis-monitor-grafana-1414429443-gs3nl    1/1       Running   0          1h
deis-monitor-influxdb-815285489-sgr4r    1/1       Running   0          1h
deis-monitor-telegraf-6zfbq              1/1       Running   1          1h
deis-monitor-telegraf-k595s              1/1       Running   0          1h
deis-monitor-telegraf-sknt5              1/1       Running   1          1h
deis-nsqd-3930557253-z4qxb               1/1       Running   0          1h
deis-registry-586278856-l2d6v            1/1       Running   3          1h
deis-registry-proxy-4pr39                1/1       Running   0          1h
deis-registry-proxy-ghb8x                1/1       Running   0          1h
deis-registry-proxy-vx3pr                1/1       Running   0          1h
deis-router-2483604242-hnzj7             1/1       Running   0          1h
deis-workflow-manager-2052159092-2mw66   1/1       Running   0          1h
```

I got these errors comming from the regitry:

```
00.96.1.4 - - [08/Aug/2017:17:10:55 +0000] "PUT /v2/bancadev/blobs/uploads/28c15d29-3eef-455a-afce-395cdc42d7c8?_state=KPw53D9-C9NBgB0qYGh0dZkiC5vBORjYSgu1R0Bx1lp7Ik5hbWUiOiJiYW5jYWRldiIsIlVVSUQiOiIyOGMxNWQyOS0zZWVmLTQ1NWEtYWZjZS0zOTVjZGM0MmQ3YzgiLCJPZmZzZXQiOjQyNTY4Njc0LCJTdGFydGVkQXQiOiIyMDE3LTA4LTA4VDE3OjEwOjMzWiJ9&digest=sha256%3Ae0ccf053d3ebaecfd921b7eb83d046a6b23f768b8dfccfef03c27113c69cc59e HTTP/1.0" 500 117 "" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.65-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)"

100.96.1.4 - - [08/Aug/2017:17:11:01 +0000] "PUT /v2/bancadev/blobs/uploads/d49f9fdf-5552-4c6c-abce-decd3476a9f8?_state=7hDOeUNbate3LsHq4yaBQz6Q7v31KPjqDH9VmnG3HcZ7Ik5hbWUiOiJiYW5jYWRldiIsIlVVSUQiOiJkNDlmOWZkZi01NTUyLTRjNmMtYWJjZS1kZWNkMzQ3NmE5ZjgiLCJPZmZzZXQiOjM4MDIyODcwLCJTdGFydGVkQXQiOiIyMDE3LTA4LTA4VDE3OjEwOjM3WiJ9&digest=sha256%3A133c45521c79493cc98b9c7810bd4d3321309c2d6d6ee3ed94386f13bf049364 HTTP/1.0" 500 117 "" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.65-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)"

100.96.1.4 - - [08/Aug/2017:17:11:18 +0000] "PUT /v2/bancadev/blobs/uploads/44b3c7a7-f087-41c8-bd19-ca9b00815824?_state=Vg5bbbamUtL0A81zM6m-K2y6TJwE3oFWVVNhoJy-Kih7Ik5hbWUiOiJiYW5jYWRldiIsIlVVSUQiOiI0NGIzYzdhNy1mMDg3LTQxYzgtYmQxOS1jYTliMDA4MTU4MjQiLCJPZmZzZXQiOjEzMDAxMDUwNSwiU3RhcnRlZEF0IjoiMjAxNy0wOC0wOFQxNzoxMDozNFoifQ%3D%3D&digest=sha256%3A91e10c1b0f05ff894e92edcc9ae890843370e660cfc81c3095d9dce628bbf0d3 HTTP/1.0" 500 117 "" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.65-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)"

100.96.1.4 - - [08/Aug/2017:17:11:35 +0000] "PUT /v2/bancadev/blobs/uploads/7aa2aed1-1acc-4cbd-96b6-d71000c46d0c?_state=IGO1j0fBmq2pFAJfxHjuZakSs8whgkmusFl9-WpHkHt7Ik5hbWUiOiJiYW5jYWRldiIsIlVVSUQiOiI3YWEyYWVkMS0xYWNjLTRjYmQtOTZiNi1kNzEwMDBjNDZkMGMiLCJPZmZzZXQiOjQyNTY4Njc0LCJTdGFydGVkQXQiOiIyMDE3LTA4LTA4VDE3OjExOjE1WiJ9&digest=sha256%3Ae0ccf053d3ebaecfd921b7eb83d046a6b23f768b8dfccfef03c27113c69cc59e HTTP/1.0" 500 117 "" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.65-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)"
100.96.1.4 - - [08/Aug/2017:17:11:36 +0000] "PUT /v2/bancadev/blobs/uploads/53c1ac25-883a-47b5-a4b0-199f632bb75e?_state=gY4ccbx3Y8gq2rXu2SsyKCgBxaRXZgxRUgh2gKsy7GR7Ik5hbWUiOiJiYW5jYWRldiIsIlVVSUQiOiI1M2MxYWMyNS04ODNhLTQ3YjUtYTRiMC0xOTlmNjMyYmI3NWUiLCJPZmZzZXQiOjUxNDg2Mjg4LCJTdGFydGVkQXQiOiIyMDE3LTA4LTA4VDE3OjExOjE0WiJ9&digest=sha256%3Abc2a558c8dfcfa7798a555b9677e0c9e8bf7c58274f4c690a12fce2db3414d0f HTTP/1.0" 500 117 "" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.65-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)"
100.96.1.4 - - [08/Aug/2017:17:11:40 +0000] "PUT /v2/bancadev/blobs/uploads/874c841c-e7ae-42be-8c2c-71d8258100d4?_state=v4COvEzw4y5whdM8GwvRDDnvOpc-VD6NdpqAXW10Fpt7Ik5hbWUiOiJiYW5jYWRldiIsIlVVSUQiOiI4NzRjODQxYy1lN2FlLTQyYmUtOGMyYy03MWQ4MjU4MTAwZDQiLCJPZmZzZXQiOjM4MDIyODcwLCJTdGFydGVkQXQiOiIyMDE3LTA4LTA4VDE3OjExOjIxWiJ9&digest=sha256%3A133c45521c79493cc98b9c7810bd4d3321309c2d6d6ee3ed94386f13bf049364 HTTP/1.0" 500 117 "" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/4.4.65-k8s os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)"
```

**Comment by bacongobbler** [comment] 2017-08-08 17:33
I assume this is the same issue we are seeing at https://github.com/deis/workflow/issues/826, and it looks like you've already commented on that issue. I'm going to close this ticket as a duplicate of that one so we can keep the discussion all in one ticket. Thanks!

**Closed by bacongobbler** 2017-08-08 17:33 UTC

**Comment by robeferre** [comment] 2017-08-08 17:40
ok Cheers @bacongobbler
