### ISSUE TITLE
On kube-aws (coreos) deis logs doesn't output stdout from the container

### ISSUE THREAD

**Issue by jwalters-gpsw** [deis/workflow#624] opened 2016-11-30 14:11 UTC
On kube-aws (coreos) "deis logs" doesn't output stdout from the container.
This is odd since we are seeing stderr output in "deis logs". Or at least the python exceptions.

Recommendations for debugging welcome.

This is Deis v2.8 and k8s 1.4.3. Also has the nodePort patch for the insecure registry problem with kube-aws.

**Comment by bacongobbler** [comment] 2017-01-04 00:16
Since the log collection agent is [fluentd](https://github.com/deis/fluentd), I would start there. I don't have too much intimate knowledge about it, but from what I understand it reads logs mounted into the fluentd filesystem through [/var/log/containers](https://github.com/deis/fluentd/blob/a5107562e9700b40b45638fc12fe7c8566883358/rootfs/opt/fluentd/sbin/sources#L2-L13), which is mounted in from the host [here](https://github.com/deis/fluentd/blob/a5107562e9700b40b45638fc12fe7c8566883358/charts/fluentd/templates/logger-fluentd-daemon.yaml#L52-L54). deis/fluentd#77 may also be relevant here.

**Comment by bacongobbler** [comment] 2017-01-10 18:59
ping @jwalters-gpsw, any update on your debugging?

**Comment by bacongobbler** [comment] 2017-01-10 19:21
This is quite likely a duplicate of https://github.com/deis/logger/issues/50. Let me know if that resolves the issue for you.

**Comment by bacongobbler** [comment] 2017-01-11 18:07
Closing for now, please re-open if you get the chance to take a look at deis/logger#50 and it doesn't work for you. Thanks!

**Closed by bacongobbler** 2017-01-11 18:07 UTC
Labels: bug
