### ISSUE TITLE
`gzip: stdin: unexpected end of file` while building the example go app

### ISSUE THREAD

**Issue by StaymanHou** [deis/workflow#192] opened 2016-04-25 19:32 UTC
I followed along the tutorials. And when I try to deploy the first example app [according to this](https://github.com/deis/workflow/blob/master/src/using-workflow/using-buildpacks.md), I got this:

```
$ git push deis master
Counting objects: 80, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (75/75), done.
Writing objects: 100% (80/80), 17.83 KiB | 0 bytes/s, done.
Total 80 (delta 33), reused 0 (delta 0)
Starting build... but first, coffee!
...
...
...
...
...
...
...
...
...
...
...
2016/04/25 18:36:51 Successfully copied home/iconic-villager:git-779ca3d7/tar to /tmp/slug.tgz
-----> Go app detected
-----> Checking Godeps/Godeps.json file.

gzip: stdin: unexpected end of file
tar: Child returned status 1
remote: 2016/04/25 18:37:12 Error running git receive hook [Build pod exited with code 2, stopping build.]
tar: Error is not recoverable: exiting now
```

Version:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
```

```
$ helm --version
helm version 0.6.0+1c8688e
```

```
$ deis version
2.0.0-dev-852b0b0
```

```
$ cd example-go
$ git log -1
commit 779ca3d7c6e4992783d4398499d34474fa55398a
Merge: 5450cbc cd6589c
Author: Matt Boersma <mboersma@deis.com>
Date:   Wed Mar 2 10:21:26 2016 -0700

    Merge pull request #13 from mboersma/golang-1.6
    
    chore(Godeps.json): update to go 1.6

```

**Comment by kmala** [comment] 2016-04-25 19:40
i think this is a known issue https://github.com/deis/slugbuilder/issues/50 and the issue is happening is because of the curl not working properly in the go slug which got fixed in https://github.com/heroku/heroku-buildpack-go/pull/117  and it uptaken our side in the https://github.com/deis/slugbuilder/pull/55
are you facing the issue consistently?

**Comment by StaymanHou** [comment] 2016-04-25 19:59
Hi @kmala. Thanks for the prompt reply. The issue is consistent for me. I also tried to deploy a php app and a ruby app with buildpack. Here's what I've got.

```
$ cd example-php
$ git push deis master
Counting objects: 3, done.
Writing objects: 100% (3/3), 244 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
Starting build... but first, coffee!
2016/04/25 19:47:47 Successfully copied home/exotic-windmill:git-62c53fa3/tar to /tmp/slug.tgz
-----> PHP app detected
-----> Bootstrapping...

gzip: stdin: unexpected end of file
tar: Child returned status 1
remote: 2016/04/25 19:48:09 Error running git receive hook [Build pod exited with code 2, stopping build.]
tar: Error is not recoverable: exiting now
```

```
$ cd example-ruby 
$ git push deis master 
Counting objects: 4, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 3.70 KiB | 0 bytes/s, done.
Total 4 (delta 0), reused 0 (delta 0)
Starting build... but first, coffee!
2016/04/25 19:53:24 Successfully copied home/breezy-jamboree:git-5370f921/tar to /tmp/slug.tgz
-----> Ruby app detected
/tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/shell_helpers.rb:49:in `run!': Command: 'set -o pipefail; curl -L --fail --retry 3 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/bundler-1.11.2.tgz -s -o - | tar zxf - ' failed unexpectedly: (LanguagePack::Fetcher::FetchError)

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/fetcher.rb:24:in `fetch_untar'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/helpers/bundler_wrapper.rb:118:in `block (2 levels) in fetch_bundler'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/helpers/bundler_wrapper.rb:117:in `chdir'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/helpers/bundler_wrapper.rb:117:in `block in fetch_bundler'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:16:in `instrument'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/helpers/bundler_wrapper.rb:84:in `instrument'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/helpers/bundler_wrapper.rb:114:in `fetch_bundler'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/helpers/bundler_wrapper.rb:33:in `install'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/ruby.rb:31:in `bundler'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/rails5.rb:9:in `block in use?'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:16:in `instrument'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/base.rb:48:in `instrument'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/rails5.rb:8:in `use?'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack.rb:17:in `block (2 levels) in detect'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack.rb:16:in `each'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack.rb:16:in `detect'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack.rb:16:in `block in detect'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:16:in `instrument'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack.rb:13:in `detect'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/bin/compile:12:in `block in <main>'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:35:in `call'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:35:in `block in trace'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:16:in `instrument'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:35:in `trace'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/bin/compile:11:in `<main>'
       !
       !     Command: 'set -o pipefail; curl -L --fail --retry 3 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/bundler-1.11.2.tgz -s -o - | tar zxf - ' failed unexpectedly:
       !
       !     gzip: stdin: unexpected end of file
       !     tar: Child returned status 1
       !     tar: Error is not recoverable: exiting now
remote: 2016/04/25 19:54:48 Error running git receive hook [Build pod exited with code 1, stopping build.]
       !
```

**Comment by StaymanHou** [comment] 2016-04-25 20:06
Hmm... Interesting.

I can successfully run the following command locally. `curl -L --fail --retry 3 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/bundler-1.11.2.tgz -s -o - | tar zxf - `

Maybe some network configuration issue? I'm using AWS as the provider. Followed the [Quick Start Guide](https://github.com/deis/workflow/blob/master/src/installing-workflow/quickstart.md) with everything default.

**Comment by bacongobbler** [comment] 2016-04-25 20:08
@StaymanHou 9 times out of 10 this issue was network related, at least for v1. It's an odd error because the ruby buildpack pipes the bundler install command (`curl -L --fail --retry 3 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/bundler-1.11.2.tgz -s -o -`, in this case) immediately into `tar` to extract it, swallowing the error.

**Comment by kmala** [comment] 2016-04-25 20:09
yes it seems to be networking issue...can try to exec into any of the container and see if the you are able to ping or curl anything....best thing would be to `kubectl exec —namespace=deis <builder-pod> <curl/ping>`

**Comment by StaymanHou** [comment] 2016-04-25 20:12
```
$ kubectl exec --namespace=deis deis-builder-x8x0f curl https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/bundler-1.11.2.tgz
curl: (6) Couldn't resolve host 's3-external-1.amazonaws.com'
```

**Comment by bacongobbler** [comment] 2016-04-25 20:14
@StaymanHou can you check /etc/resolv.conf inside the pod? Interesting that the pod does cannot resolve for s3 unless DNS is not set up correctly.

**Comment by StaymanHou** [comment] 2016-04-25 20:14
```
$ kubectl exec --namespace=deis deis-builder-x8x0f cat /etc/resolv.conf   
search deis.svc.cluster.local svc.cluster.local cluster.local us-west-2.compute.internal
nameserver 10.0.0.10
options ndots:5
```

**Comment by bacongobbler** [comment] 2016-04-25 20:18
This seems relevant: https://github.com/kubernetes/kubernetes/issues/16836

**Comment by StaymanHou** [comment] 2016-04-25 21:48
I'm able to resolve this issue by disabling k8s cluster dns. `export KUBE_ENABLE_CLUSTER_DNS=false`.

As of k8s v1.2.2, the aws bootstrap script enables cluster dns by default, but it doesn't install [dns addon](https://github.com/kubernetes/kubernetes/tree/release-1.2/cluster/addons/dns). As a result, dns doesn't work in the pods by default for aws k8s cluster.

**Comment by StaymanHou** [comment] 2016-04-25 21:49
Thank you very much. :+1:  Closing the issue.

**Closed** 2016-04-25 21:49 UTC
Labels: bug
