### ISSUE TITLE
controller should fail gracefully when app namespaces already exist

### ISSUE THREAD

**Issue by arschles** [deis/workflow#262] opened 2016-01-11 18:12 UTC
at the very least, it should return an error code in `/v2/hooks/build` (perhaps `409 Conflict`). Here are logs for such a case:

```console
DEBUG scale gotest_v2.web, img gotest:git-165e2360d0de236cfe4eecec6efadf66606efe37, params {'healthcheck': {'timeout': 1, 'port': 8080, 'path': '/', 'delay': 10}, 'cpu': {}, 'memory': {}, 'num': 1, 'envs': {}, 'version': 'v2', 'tags': {}, 'app_type': 'web', 'aname': 'gotest'}, cmd "start web"
DEBUG create gotest_v2.web, img gotest:git-165e2360d0de236cfe4eecec6efadf66606efe37, params {'healthcheck': {'timeout': 1, 'port': 8080, 'path': '/', 'delay': 10}, 'cpu': {}, 'memory': {}, 'num': 1, 'envs': {}, 'version': 'v2', 'tags': {}, 'app_type': 'web', 'aname': 'gotest'}, cmd "start web"
DEBUG failed to create Namespace gotest: 409 Conflict
{'code': 409, 'kind': 'Status', 'reason': 'AlreadyExists', 'message': 'namespaces "gotest" already exists', 'status': 'Failure', 'details': {'kind': 'namespaces', 'name': 'gotest'}, 'metadata': {}, 'apiVersion': 'v1'}
ERROR gotest: gotest_v2.web (scale): failed to get ReplicationController "gotest-v2-web" in Namespace "gotest": 404 Not Found
{'code': 404, 'kind': 'Status', 'reason': 'NotFound', 'message': 'replicationControllers "gotest-v2-web" not found', 'status': 'Failure', 'details': {'kind': 'replicationControllers', 'name': 'gotest-v2-web'}, 'metadata': {}, 'apiVersion': 'v1'}
ERROR [gotest]: gotest_v2.web (scale): failed to get ReplicationController "gotest-v2-web" in Namespace "gotest": 404 Not Found
{'code': 404, 'kind': 'Status', 'reason': 'NotFound', 'message': 'replicationControllers "gotest-v2-web" not found', 'status': 'Failure', 'details': {'kind': 'replicationControllers', 'name': 'gotest-v2-web'}, 'metadata': {}, 'apiVersion': 'v1'}
```

**Comment by helgi** [comment] 2016-02-25 00:49
This one is a duplicate of #316 - that one has better information

**Closed by helgi** 2016-02-25 00:49 UTC
Labels: bug
