### ISSUE TITLE
App pod in CrashLoopBackOff after deploy

### ISSUE THREAD

**Issue by krancour** [deis/workflow#133] opened 2015-12-18 05:50 UTC
This appears to be the cause:

```
core@ip-10-0-0-236 ~ $ docker logs e9fae214adef
+ export HOME=/app
+ HOME=/app
+ mkdir -p /app
++ ls -A /app
+ [[ -n '' ]]
+ [[ -n http://10.3.0.212:9000/git/home/molten-zirconia:git-6dc0e3bc/slug ]]
+ [[ -e /var/run/secrets/object/store/access-key-id ]]
+ tar -xzC /app
+ curl -s http://10.3.0.212:9000/git/home/molten-zirconia:git-6dc0e3bc/slug

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by bacongobbler** [comment] 2015-12-18 05:52
dupe of deis/slugrunner#6 :)

**Closed** 2015-12-18 06:49 UTC
