### ISSUE TITLE
Error from server: error when creating "STDIN": secrets "builder-ssh-private-keys" already exists

### ISSUE THREAD

**Issue by olalonde** [deis/workflow#384] opened 2016-07-20 01:26 UTC
I am following the install steps at https://deis.com/docs/workflow/ to setup k8s + deis v2.

At the https://deis.com/docs/workflow/installing-workflow/configuring-object-storage/ step, I followed the instructions up to

> You are now ready to helmc install workflow-v2.1.0 using your desired object storage.

```bash
$ export STORAGE_TYPE=s3
# etc.
$ helmc generate -x manifests workflow-v2.1.0
[ERROR] File /Users/olalonde/.helmc/workspace/charts/workflow-v2.1.0/manifests/deis-builder-rc.yaml already exists. To overwrite it, please re-run this command with the --force/-f flag.
[ERROR] Failed to complete generation: failed to execute helm template -o /Users/olalonde/.helmc/workspace/charts/workflow-v2.1.0/manifests/deis-builder-rc.yaml -d /Users/olalonde/.helmc/workspace/charts/workflow-v2.1.0/tpl/generate_params.toml /Users/olalonde/.helmc/workspace/charts/workflow-v2.1.0/tpl/deis-builder-rc.yaml (/Users/olalonde/.helmc/workspace/charts/workflow-v2.1.0/tpl/deis-builder-rc.yaml): exit status 1
$ helmc generate -f -x manifests workflow-v2.1.0 
---> Ran 16 generators.
```

And am getting this error when running `helmc install workflow-v2.1.0`:

```
$ helmc install workflow-v2.1.0
---> Running `kubectl create -f` ...
namespace "deis" configured

Error from server: error when creating "STDIN": secrets "builder-ssh-private-keys" already exists

[ERROR] Failed to upload manifests: exit status 1
```

I assume that's because I already previously installed deis at https://deis.com/docs/workflow/installing-workflow/. At this step, it's not clear to me whether I should uninstall deis and start again or if there's any way to update the configuration. Since I assume most people will get to the `Configuring Object Storage` just after installing Deis, it would be useful to have information on how to do that in that page.

**Comment by olalonde** [comment] 2016-07-20 06:34
It seems the solution at the moment (according to Slack channel reply) is to uninstall and install again: `helmc uninstall workflow-v2.1.0 && helmc install workflow-v2.1.0`. Guess this issue can be closed but maybe it'd be a good idea to mention this more visibly in the docs.

**Comment by olalonde** [comment] 2016-07-20 06:39
There seems to be an alternative way of modifying deis env variables [mentioned here](https://deis.com/docs/workflow/users/registration/#controlling-registration-modes): `kubectl --namespace=deis edit rc deis-controller`, not sure what the conceptual difference is though.

**Comment by bacongobbler** [comment] 2016-10-04 05:43
I think it's safe to close this one out as resolved since we have extensively rewritten the installation docs since v2.1.0.

**Closed by bacongobbler** 2016-10-04 05:43 UTC
Labels: docs

**Comment by vkrishnasamy** [comment] 2016-10-13 12:33
I guess the issue is helmc install of workflow is 'not idempotent'. May be it is not intended to be. In my view it should be with a command to overwrite. Problem is because once the k8 namespace is created it is unable to re-run on them again.

**Comment by vkrishnasamy** [comment] 2016-10-13 12:40
please give this a shot. It worked for me. do it couple of times if required. and then install again.

helmc uninstall workflow-v2.7.0 -n deis --force

helmc install workflow-v2.7.0
