### ISSUE TITLE
Wrong healthcheck port used when it's a slug runner

### ISSUE THREAD

**Issue by aledbf** [deis/workflow#373] opened 2016-02-15 15:53 UTC
The application [template](https://github.com/deis/workflow/blob/master/rootfs/scheduler/__init__.py#L128) uses port `5000` but the [healthckeck](https://github.com/deis/workflow/blob/master/rootfs/api/models/config.py#L34) port is `8080`

**Comment by helgi** [comment] 2016-02-15 21:03
It doesn't use two ports instead we look at if the port is already defined and use that: https://github.com/deis/workflow/blob/master/rootfs/scheduler/__init__.py#L702 so in the example above you should get port 5000 for healthcheck.

If it possible that this changed it https://github.com/deis/workflow/commit/91228fde692d4bce0b97c84508a68d3cefe14259#diff-3b6e1f09121075ad67f216aa2bbfc9a6 since I used to have it look at the `PORT` env var and utilise that but now it looks at the `targetPort` which should work as well.

Have you booted up an app and checked if the healthcheck is wrong? I can otherwise check tomorrow

**Comment by aledbf** [comment] 2016-02-15 21:05
> Have you booted up an app and checked if the healthcheck is wrong

@helgi yes, it generates 8080 as health check port

**Comment by helgi** [comment] 2016-02-15 21:12
Alright, that's a bug then which the above PR introduced it looks like

Thanks for catching it :)

**Comment by helgi** [comment] 2016-02-15 21:42
@aledbf I just want to verify what kind of application types you tried this with

**Comment by aledbf** [comment] 2016-02-15 21:49
@helgi node.js app with Procfile - web type

**Comment by helgi** [comment] 2016-02-15 22:29
@smothiki should be able to shed light on it since he had the PR that changed this around.

**Comment by smothiki** [comment] 2016-02-16 18:39
I dont think readiness probess are failing due to wring health check port 
Just created an APP example ruby 
```
$ kubectl get pod -o yaml preset-waxworks-v2-web-dixkj --namespace=preset-waxworks
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicationController","namespace":"preset-waxworks","name":"preset-waxworks-v2-web","uid":"e07fe1c3-d4db-11e5-a701-0644c2891049","apiVersion":"v1","resourceVersion":"2393"}}
  creationTimestamp: 2016-02-16T18:34:13Z
  generateName: preset-waxworks-v2-web-
  labels:
    app: preset-waxworks
    heritage: deis
    type: web
    version: v2
  name: preset-waxworks-v2-web-dixkj
  namespace: preset-waxworks
  resourceVersion: "2494"
  selfLink: /api/v1/namespaces/preset-waxworks/pods/preset-waxworks-v2-web-dixkj
  uid: e081388d-d4db-11e5-a701-0644c2891049
spec:
  containers:
  - args:
    - start
    - web
    env:
    - name: PORT
      value: "5000"
    - name: SLUG_URL
      value: http://10.3.0.212:9000/git/home/preset-waxworks:git-e1590887/push/slug.tgz
    - name: DEBUG
      value: "1"
    - name: DEIS_APP
      value: preset-waxworks
    - name: DEIS_RELEASE
      value: v2
    - name: DOCKERIMAGE
      value: "1"
    image: quay.io/deisci/slugrunner:v2-beta
    imagePullPolicy: Always
    livenessProbe:
      httpGet:
        path: /
        port: 5000
        scheme: HTTP
      initialDelaySeconds: 10
      timeoutSeconds: 1
    name: preset-waxworks-web
    readinessProbe:
      httpGet:
        path: /
        port: 5000
        scheme: HTTP
      initialDelaySeconds: 10
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    volumeMounts:
    - mountPath: /var/run/secrets/object/store
      name: minio-user
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-r7dku
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: ip-10-0-0-178.us-west-2.compute.internal
  restartPolicy: Always
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: minio-user
    secret:
      secretName: minio-user
  - name: default-token-r7dku
    secret:
      secretName: default-token-r7dku
status:
  conditions:
  - status: "False"
    type: Ready
  containerStatuses:
  - containerID: docker://0b7ec83f29bd397bce0fe141d4d25d192bbd5eea7af09816980be3ce00e41573
    image: quay.io/deisci/slugrunner:v2-beta
    imageID: docker://bfc3e9335c6bd79659da5db384cc887a277bbe3d085e6962d5073d2dbbcb7428
    lastState:
      terminated:
        containerID: docker://0b7ec83f29bd397bce0fe141d4d25d192bbd5eea7af09816980be3ce00e41573
        exitCode: 1
        finishedAt: 2016-02-16T18:36:14Z
        reason: Error
        startedAt: 2016-02-16T18:36:13Z
    name: preset-waxworks-web
    ready: false
    restartCount: 2
    state:
      terminated:
        containerID: docker://0b7ec83f29bd397bce0fe141d4d25d192bbd5eea7af09816980be3ce00e41573
        exitCode: 1
        finishedAt: 2016-02-16T18:36:14Z
        reason: Error
        startedAt: 2016-02-16T18:36:13Z
      waiting:
        reason: CrashLoopBackOff
  hostIP: 10.0.0.178
  phase: Running
  podIP: 10.2.77.5
  startTime: 2016-02-16T18:34:13Z
```

**Comment by helgi** [comment] 2016-02-16 18:41
As long as the `healthcheck` port is `5000` as expected then we should be fine. Maybe that app is diff in some way than what @aledbf used? Hmmmm

**Comment by smothiki** [comment] 2016-02-16 18:43
But I dont have any luck starting the APP. readiness probes are failing continuously. I'll try increasing the initial delay and timeouts for readiness probes

**Comment by mboersma** [comment] 2016-02-16 18:46
I think this is a duplicate of #367, just FYI.

**Comment by smothiki** [comment] 2016-02-17 18:49
Closing this issue in favor of https://github.com/deis/workflow/issues/367

**Closed by smothiki** 2016-02-17 18:49 UTC
Labels: bug
